controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_events:
    path: /events
    controller: App\Controller\EventController::getEvents
    methods: GET

app_events_create:
    path: /events
    methods: [ POST ]
    controller: App\Controller\EventController::createEvent
